### ISSUE TITLE
how do you think replacing webpack with Vite

### ISSUE THREAD

**Issue by Germiniku** [faasjs/starter#187]
vite build much faster than webpack,and now vite is used in many projects

**Comment by zfben** [comment]
yes, in fact, I am trying vite in my new project.

welcome to replace webpack with vite for this project if you have time 👍

**Comment by Germiniku** [comment]
ok,I will find time to replace webpack with vite.

**Comment by Germiniku** [comment]
I have a problem with jest.vite environment introduced for use is `import.meta.env`. 
`public.faas.tsx` use import.meta.env.REACT_APP_API, jest throw one Error `    SyntaxError: Cannot use 'import.meta' outside a module`
**babel** was the only solution I found, but no **swc** solution was found

**Comment by Germiniku** [comment]
I found a great method to resolve this problem.
[stackoverflow](https://stackoverflow.com/questions/68317339/testing-svelte-components-with-import-meta-env)

**Comment by zfben** [comment]
@Germiniku thank you for your work, for jest, faasjs includes `@faasjs/jest`, can you try it?

**Comment by Germiniku** [comment]
> @Germiniku thank you for your work, for jest, faasjs includes `@faasjs/jest`, can you try it?

I don't try `@faasjs/jest`,I found github and stackoverflow,some methods is use babel plugin. transform import.meta.env to process.env,but use @swc/jest,I‘m not be familiar with swc.
**Jest** is the common specification, and the common specification does not support ESM,**ts-jest** seems to have the same problem.

**Comment by zfben** [comment]
> I have a problem with jest.vite environment introduced for use is `import.meta.env`. `public.faas.tsx` use import.meta.env.REACT_APP_API, jest throw one Error ` SyntaxError: Cannot use 'import.meta' outside a module` **babel** was the only solution I found, but no **swc** solution was found

When did you get the problem? I didn't reproduce it, my ci log is here: https://github.com/faasjs/starter/actions/runs/1967724815

**Comment by Germiniku** [comment]
> 
`www/src/libs/faas.tsx`
 `www/vite.config.ts`
**define** in vite.config.ts! I had transform vite .env `import.meta.env.VITE_REACT_APP_API` to process.env.VITE_REACT_APP_API.Then jest test is successfully.

**Comment by Germiniku** [comment]
if I use `import.meta.env.VITE_REACT_APP_API` in `libs/faas.tsx`,jest will failure.

**Comment by zfben** [comment]
I mock the `libs/faas` to skip the issue, because I think for web testing, mock data is good enough.

What do you think?

**Comment by Germiniku** [comment]
I think this is good enough,but if use test api,how to set.

**Comment by Germiniku** [comment]
It is so cool,need to remove `vite.config.ts` transform.
